name: Daily Report

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write # トリガーするためにactions権限を追加

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv sync
      - name: set locale to ja_JP.UTF-8
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
      - name: Generate report
        run: ./generate-report.sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          LANG: ja_JP.UTF-8
          TZ: "Asia/Tokyo"
      - name: Configure git
        run: |
          git config --global user.email "autotaker@gmail.com"
          git config --global user.name "autotaker"
      - name: Commit and push changes
        id: commit_and_push
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Generate daily report" && git push
      - name: Trigger gh_pages workflow
        if: steps.commit_and_push.outcome == 'success'
        run: gh workflow run gh_pages.yaml
        env:
          GITHUB_TOKEN: ${{ github.token }}
