name: Build and Deploy Site

# このワークフローは main ブランチへのプッシュ時にトリガーされます
on:
  push:
    branches:
      - main
    paths:
      - "site/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Haskell 環境をセットアップ
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4" # Resolves to the latest point release of GHC 8.8
          cabal-version: "3.6"

      # Cabal を更新
      - name: Update Cabal
        run: cabal update

      # `site` ディレクトリに移動してビルド
      - name: Build site
        working-directory: ./site
        run: |
          cabal build
          cabal run diff-insight-site-generator build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
